version: '3.8'

services:
  database_api:
    image: postgres
    container_name: database_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=volimed_api
    volumes:
      - ./infra_local/pg_data:/var/lib/postgresql/data
