CREATE TABLE medicos (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    crm VARCHAR(100) NOT NULL UNIQUE,
    specialist VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    city VARCHAR(100) NOT NULL
);
